name: build

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    name: ğŸ¤– Build Android APK

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: â˜•ï¸ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: ğŸ› ï¸ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.38.5'
          cache: true

      - name: ğŸ“¦ Install dependencies
        run: flutter pub get

      - name: ğŸ§  Generate code
        run: |
          flutter gen-l10n
          dart run build_runner build --delete-conflicting-outputs

      - name: ğŸ” Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE_BASE64" | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: ğŸ“ Update key.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: |
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEYSTORE_ALIAS" >> android/key.properties
          echo "storeFile=${{ github.workspace }}/keystore.jks" >> android/key.properties
        shell: bash

      - name: ğŸ—ï¸ Build APK
        run: flutter build apk --target-platform android-arm64

      - name: ğŸ“¤ Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
